fix: 학번 로직 개선
BCSDLab/KOIN_WEB pull request #202
Opened 2022-09-14 06:29 UTC by jaewoogwak

기존에 10자리 학번에서 5, 6, 7번째 자리를(ex: 2019'136'009) 가져와서 검증했으나, 사실 학번 구분은 6,7번째 2자리로 하는 것이었습니다.
https://github.com/BCSDLab/KOIN_WEB/issues/201

따라서 입력받은 학번 문자열을 3자리로 자르던것을 2자리로 잘라서 검증하게 바꾸었습니다.

_기존에는 디자인과 건축공학부를 구분하지 않고 151로 동일하게 처리했었는데, 건축공학부는 따로 72라는 학번 구분이 존재.

그래서 건축공학부 학생이 학번(2019172...)을 입력하면 학부 자동 입력 기능이 작동하지 않았음._

이 부분은 백엔드 측에서 학번 API를 추가함에따라 API 요청을 통해 학번 리스트를 받아올 수 있게 되어 해결되었습니다.

또한 기존에는 학번 데이터를 static/major.js와 같이 정적으로 가지고 있었는데 이제 API 요청을 통해 학번을 가져올 수 있어서

학번 데이터인 major.js를 삭제하였습니다.

2022-09-14 06:45 UTC, D0Dam reviewed
수고 많으셨습니다! 개인적으로 궁금한 사항들 질문 남겨봅니다!😁

2022-09-14 06:45 UTC, D0Dam commented on src/containers/UserContainers/ModifyInfoContainer.js
> +import axios from 'axios';
이 로직 개선하면서 api를 받아올 때  axios라이브러리를 추가적으로 포함시킨건가요??

2022-09-14 06:45 UTC, D0Dam commented on src/containers/UserContainers/ModifyInfoContainer.js
> +        if (major.dept_nums.includes(majorCode)) {
원래 다른 변수명들은 Camel 표기법으로 되어있었는데 `stdent_number_list`와 `dept_nums`는 Snake 표기법이네요..! 이렇게  한 이유가 있을까요?

2022-09-14 06:54 UTC, jaewoogwak commented on src/containers/UserContainers/ModifyInfoContainer.js
> +        if (major.dept_nums.includes(majorCode)) {
dept_nums는 API 호출해서 받아온 배열에 학번 정보 담긴 객체 프로퍼티가 depts_nums : ["36"] 과 같은 형태라서 
스네이크 표기법으로 했고 student_number_list는 카멜 표기법으로 수정하겠습니다.

2022-09-14 06:58 UTC, HAEROOL commented on src/containers/UserContainers/ModifyInfoContainer.js
> +  const student_number_list = useRef([]);
`useRef`를 사용하신건 리렌더링 하지 않고 데이터를 받아오기 위해서인가요??

2022-09-14 07:02 UTC, jaewoogwak commented on src/containers/UserContainers/ModifyInfoContainer.js
> +  const student_number_list = useRef([]);
네 맞습니다. 그리고 학번이 렌더링하는데에 있어서 불필요한 데이터라고 생각해서 `useState`가 아닌 `useRef`를 사용하였습니다.

2022-09-14 07:02 UTC, jaewoogwak commented on src/containers/UserContainers/ModifyInfoContainer.js
> +        if (major.dept_nums.includes(majorCode)) {
[b68b4e5](https://github.com/BCSDLab/KOIN_WEB/pull/202/commits/b68b4e55a41b710c7c9665d38b86e38f475f8ea7) 수정완료했습니당

2022-09-14 07:06 UTC, jaewoogwak commented on src/containers/UserContainers/ModifyInfoContainer.js
> +import axios from 'axios';
기존에 다른 컴포넌트에서도 axios를 사용해서 해당 컴포넌트에서도 axios 임포트 시켜서 사용하였습니다.

2022-09-14 07:12 UTC, D0Dam approved these changes

2022-09-14 09:03 UTC, hanagertrudekim reviewed
수고하셨습니다! 한가지 궁금한점에 대해 질문 남겼습니다

2022-09-14 09:03 UTC, hanagertrudekim commented on src/containers/UserContainers/ModifyInfoContainer.js
>      e.preventDefault();
preventDefault를 한 이유가 뭔가요?

2022-09-14 09:04 UTC, ChoiWonBeen requested changes
api위치 변경이 필요하고,
현재 학번 중간에서 변경시 학과값이 초기화되지 않습니다.
서버단에서 에러로 처리해주지만, UX를 위해 값의 변경에 바로 적용되게 하는 것이 좋아보입니다.

2022-09-14 09:04 UTC, ChoiWonBeen commented on src/containers/UserContainers/SignUpContainer.js
> +      axios("https://api.stage.koreatech.in/depts").then(res => {
링크를 이렇게 넣으면 .env파일에 API path를 저장하는 이유가 없어지겠죠?
거기에 실배포가 된다면 stage가 아닌, api.koreatech.in을 사용해야합니다.
이를 고려해서 api폴더에 API_PATH를 가져와 모아뒀을 겁니다. 이를 활용해주세요.

2022-09-14 09:11 UTC, ChoiWonBeen commented on src/containers/UserContainers/ModifyInfoContainer.js
>      e.preventDefault();
이번에 처음 프로젝트를 수정하셨을텐데, 변경한 부분이 아니라서 대신 말씀드리자면, form의 `onSubmit`에 담는 이벤트핸들러 함수입니다. submit의 기본적인 action은 해당 폼을 특정 url에 제출하는데, 단순 POST로 끝내는 것이 아닌, 서버에서 에러를 보내면(특정 필드가 부족하다거나, 학번이 잘못됐다거나 등..) 이를 핸들링하기 위해서 submit을 새로 정의하되, 기본 동작인 제출을 막기 위해 추가했습니다.
 
modify라는 이름이 submit의 느낌을 주지 못해서 혼동되지만, [리코드](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/14)에선 해당 부분이 개선됐습니다.

2022-09-14 09:14 UTC, hanagertrudekim commented on src/containers/UserContainers/ModifyInfoContainer.js
>      e.preventDefault();
답변 감사합니다! 이해되었습니다ㅎㅎ

2022-09-14 09:18 UTC, hanagertrudekim commented on src/containers/UserContainers/SignUpContainer.js
> +      axios("https://api.stage.koreatech.in/depts").then(res => {
질문있습니다, 이 부분에서 useEffect안에 axios를 써 재요청을 방지하는것을 대신해 react-query의 useQuery를 이용할수있지 않나요?

2022-09-14 09:22 UTC, ChoiWonBeen commented on src/containers/UserContainers/SignUpContainer.js
> +      axios("https://api.stage.koreatech.in/depts").then(res => {
이 프로젝트가 서버 데이터 fetching 라이브러리를 안써서....그렇습니다 ㅠ
전역으로 저장되고, 1회 이상 요청이 필요없는데다가 mutate와 refetch또한 필요없는 데이터라 react-query나, rtk-query를 쓰면 참 좋겠지만 사용하지 않고있고, 그래서 최소한의 최적화를 위해 localStorage에 해당 값이 있을 경우 재요청 방지라도 추가한 것 같습니다.

2022-09-14 09:29 UTC, hanagertrudekim commented on src/containers/UserContainers/SignUpContainer.js
> +      axios("https://api.stage.koreatech.in/depts").then(res => {
아하..... fetching 라이브러리를 대신 localstorage를 사용해서 재요청을 방지하는게 신기하네요ㅎㅎ.. 저의 의문점에 친절한 답변 감사합니다ㅎㅎ

2022-09-14 10:20 UTC, jaewoogwak commented on src/containers/UserContainers/SignUpContainer.js
> +      axios("https://api.stage.koreatech.in/depts").then(res => {
@ChoiWonBeen API 위치 변경이라면 useEffect의 위치를 말씀하시는건가요? 아니면 effect 내부에서 axios로 요청하는 부분의 위치를 말씀하시는건가요?

2022-09-14 10:28 UTC, ChoiWonBeen commented on src/containers/UserContainers/SignUpContainer.js
> +      axios("https://api.stage.koreatech.in/depts").then(res => {
후자입니다. api폴더에 api들이 모여있으니, 해당 파일에서 import하는 방식으로 수정해주세요.

2022-09-14 10:43 UTC, jaewoogwak commented on src/containers/UserContainers/SignUpContainer.js
> +      axios("https://api.stage.koreatech.in/depts").then(res => {
학번 수정 시 학과 값 초기화 이슈 해결 완료했습니다.
[ebc0044](https://github.com/BCSDLab/KOIN_WEB/pull/202/commits/ebc0044ff67f931d2531eb56565633519483f869)

2022-09-14 10:43 UTC, jaewoogwak commented on src/containers/UserContainers/SignUpContainer.js
> +      axios("https://api.stage.koreatech.in/depts").then(res => {
학번 리스트 얻는 함수 api 폴더로 이동시켜서 import 하는 방식으로 수정했습니다.
[9b4163d](https://github.com/BCSDLab/KOIN_WEB/pull/202/commits/9b4163d0b407b1512cf255b3af7138235856efe6)

2022-09-14 15:37 UTC, ChoiWonBeen approved these changes
고생하셨습니다 👍

2022-09-15 01:53 UTC, hexdrinker commented on src/containers/UserContainers/SignUpContainer.js
> +      axios("https://api.stage.koreatech.in/depts").then(res => {
정책이 어떤지는 모르겠는데 비동기처리 문법은 최신스펙인 async await 로 통일하면 좋을듯

2022-09-15 13:46 UTC, jaewoogwak commented on src/containers/UserContainers/SignUpContainer.js
> +      axios("https://api.stage.koreatech.in/depts").then(res => {
@hexdrinker 말씀하신대로 비동기처리 문법 async/await으로 변경하였습니다.  [b63d2d4](https://github.com/BCSDLab/KOIN_WEB/pull/202/commits/b63d2d4e478e40d95c27ddf498ee6233fb363987)

2022-09-16 15:52 UTC, merged