fix: 부자연스러운 식단 UI 개선
BCSDLab/KOIN_WEB pull request #209
Opened 2022-09-19 13:20 UTC by chaeseungyun

코인 홈 화면의 식단표에서 메뉴의 개수가 6개 이하일 때도 메뉴 이름이 ...으로 생략되는 현상을 수정하였습니다.
![image](https://user-images.githubusercontent.com/101871802/191026646-69d7d404-0611-4e60-81c7-d8842fe6e37e.png)
![image](https://user-images.githubusercontent.com/101871802/191026699-ac44f057-65d4-4dc8-bb49-7ecb3b9ce083.png)

2022-09-19 13:27 UTC, ChoiWonBeen requested changes
확인하고 수정해주세요.
오토포맷터가 켜져있어서 또 변경사항을 확인하기 쉽지 않네요.. ㅋㅋ

2022-09-19 13:27 UTC, ChoiWonBeen commented on src/components/IndexComponents/IndexCafeteria.js
> +                                let a = menu.length;
변수명... 신경써주세요 😅

2022-09-19 13:27 UTC, ChoiWonBeen commented on src/components/IndexComponents/IndexCafeteria.js
> +                                let len = `${dish}`.length;
dish.length를 쓰지 않은 이유가 있나요?

2022-09-19 13:27 UTC, ChoiWonBeen commented on src/components/IndexComponents/IndexCafeteria.js
> +                                  </Fragment>
이렇게 복잡하게 구현하지 않아도 [좋은 속성](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow)이 있어서 활용하면 좋습니다.
물론 이번엔 수정하는게 목표지만, 클린코드로 한번 바꿔보는 경험을 가지는것도 좋을거같아요.

2022-09-19 13:32 UTC, ChoiWonBeen commented on src/components/IndexComponents/IndexCafeteria.js
> +                                  </Fragment>
+len이라는 변수에 길이를 담았다가 true, false로 바꾸는것도 좋아보이진 않네요

2022-09-19 13:36 UTC, chaeseungyun commented on src/components/IndexComponents/IndexCafeteria.js
> +                                let a = menu.length;
나중에 수정하는 것을 깜빡했습니다..ㅎ

2022-09-19 13:38 UTC, chaeseungyun commented on src/components/IndexComponents/IndexCafeteria.js
> +                                let len = `${dish}`.length;
이건 제가 헷갈린 것 같아요
수정하겠습니다

2022-09-19 13:59 UTC, chaeseungyun commented on src/components/IndexComponents/IndexCafeteria.js
> +                                  </Fragment>
좋은 속성 감사합니다
수정 완료했습니다

2022-09-20 00:06 UTC, D0Dam requested changes
수고하셨습니다! 수정사항 확인해주세요~!

2022-09-20 00:06 UTC, D0Dam commented on src/components/IndexComponents/IndexCafeteria.js
>    line-height: 1.2;
여기 `line-height`가 1.2인게 의도된건가요..?

2022-09-20 00:06 UTC, D0Dam commented on src/components/IndexComponents/IndexCafeteria.js
> +  console.log(type);
이 `console.log(type)`은 지워도 될것 같습니다.

2022-09-20 00:07 UTC, jaewoogwak approved these changes

2022-09-20 03:21 UTC, chaeseungyun commented on src/components/IndexComponents/IndexCafeteria.js
>    line-height: 1.2;
제가 작업하기 전부터 있던 내용이라 제가 답변하기 힘들 것 같습니다..

2022-09-20 03:22 UTC, chaeseungyun commented on src/components/IndexComponents/IndexCafeteria.js
> +  console.log(type);
수정하겠습니다~

2022-09-20 11:02 UTC, ChoiWonBeen commented on src/components/IndexComponents/IndexCafeteria.js
>    line-height: 1.2;
line-height: 120%와 동일한 수치입니다~

2022-09-20 11:33 UTC, ChoiWonBeen approved these changes

2022-09-20 19:23 UTC, D0Dam approved these changes

2022-09-21 01:54 UTC, merged